sudo: false
# Trusty doesn't support Python 3.7 yet.
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - echo "script start"
  - ci/run_tests.sh
after_success:
  # upload code coverage report to codecov
  - bash <(curl -s https://codecov.io/bash)
